name: CustomLootChest
version: 1.0-SNAPSHOT
main: de.veraimt.customlootchest.CustomLootChest
authors: [Veraimt]
api-version: 1.8

commands:
  lootchest:
    description: Manage Lootchests
    usage: /<command> [create/load/delete] name
